

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dalton
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginFor
     */
    public LoginForm() {
        initComponents();
           
        
        Seticon();
        
       clock ();
       
       lbl_U.setVisible(false);
       
       lbl_P.setVisible(false);


    }
    
    
   public void clock (){
        
        Thread clock = new Thread(){
            
            public void run (){
                try{
                    
                        for(;;){
                        Calendar cal = new GregorianCalendar();
        
                        int day = cal.get(Calendar.DAY_OF_MONTH);
        
                        int month= cal.get(Calendar.MONTH);
        
                        int year = cal.get(Calendar.YEAR);
                        
                        int second = cal.get(Calendar.SECOND);
        
                        int minute = cal.get(Calendar.MINUTE);
        
                        int hour = cal.get(Calendar.HOUR);
                        
                        jCurrentTime.setText( hour +":" + minute + ":" + second );
                        
                        jDate.setText(day +":" + (month+1) + ":" + year );
                        
                        sleep (1000);
                        
                        }
                }
        
                        
                      
                
                catch(InterruptedException e){
                    
                    e.printStackTrace();
                }
                    
                
            }
        } ;
        
        clock.start();
        
    }
    



 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLogin = new javax.swing.JButton();
        lbl_U = new javax.swing.JLabel();
        lbl_P = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jCtime = new javax.swing.JLabel();
        jCurrentTime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("LoginFrame"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Student's Information System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 71, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jLogin.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLogin.setForeground(new java.awt.Color(51, 51, 51));
        jLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/login_ok.png"))); // NOI18N
        jLogin.setText("Login");
        jLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 90, -1));

        lbl_U.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_U.setForeground(new java.awt.Color(204, 0, 0));
        lbl_U.setText("*");
        getContentPane().add(lbl_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        lbl_P.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_P.setForeground(new java.awt.Color(153, 0, 0));
        lbl_P.setText("*");
        getContentPane().add(lbl_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        jUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(jUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 160, 30));

        jPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 160, 30));

        jCtime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCtime.setForeground(new java.awt.Color(0, 51, 51));
        jCtime.setText("Current Time :");
        getContentPane().add(jCtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jCurrentTime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCurrentTime.setForeground(new java.awt.Color(0, 51, 51));
        getContentPane().add(jCurrentTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 80, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setText("Date :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 50, -1));

        jDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDate.setForeground(new java.awt.Color(0, 51, 51));
        jDate.setText(" ");
        getContentPane().add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 100, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/LoginPageImage.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsernameActionPerformed



        // TODO add your handling code here:
    }//GEN-LAST:event_jUsernameActionPerformed

    private void jLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginActionPerformed
                    
        
                         lbl_U.setVisible(false);
       
                         lbl_P.setVisible(false);
        
        
                        if (jUsername.getText().equalsIgnoreCase("")) {
				
                        lbl_U.setVisible(true);
       
      
            
                      
			}
			
                         if(String.valueOf(jPassword.getPassword()).equalsIgnoreCase("")){
                            
                            lbl_P.setVisible(true);
                            
                        }
                         
                         
                         else{
                             
                             
                             Connection con = MyConnection.getConnection();
                             
                             PreparedStatement ps ;
                             
                             try {
                                 ps = con.prepareCall(" SELECT * FROM user WHERE Username = ? AND Password = ? ");
                                 
                                 ps.setString(1, jUsername.getText());
                                 
                                 ps.setString(2, String.valueOf(jPassword.getPassword()));
                                 
                                 ResultSet rs = ps.executeQuery();
                                 
                                 if(rs.next()){
                                     
                                     JOptionPane.showMessageDialog(null, " Login Successfully ");
                                     
                                     MainForm MF = new MainForm();
                                     
                                     MF.setVisible(true);
                                     
                                     MF.pack();
                                     
                                     MF.setLocationRelativeTo(null);
                                     
                                     MF.setExtendedState(JFrame.MAXIMIZED_BOTH);
                                     
                                     MainForm.jLabel_Username.setText("Welcome " + jUsername.getText() + " " );
                                     
                                     
                                     MainForm.jTotal_Students.setText("Total Students = "+ Integer.toString(Count.countData("student")));
                                     
                                     
                                     MainForm.jTotalCources.setText("Total Cources = "+ Integer.toString(Count.countData("course")));
                                     
                                     this.dispose();
                                 }
                                 
                                 else{
                                     
                                     JOptionPane.showMessageDialog(null, "Please input correct username and password!!  ");
                                 }
                                     
                                 
                             } catch (SQLException ex) {
                                 Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                             }
                         }
				


       
    }//GEN-LAST:event_jLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jCtime;
    private javax.swing.JLabel jCurrentTime;
    private javax.swing.JLabel jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLogin;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUsername;
    private javax.swing.JLabel lbl_P;
    private javax.swing.JLabel lbl_U;
    // End of variables declaration//GEN-END:variables

    private void Seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Programme icon2.png")));

    }
}
